### ISSUE TITLE
Todo list (features and bugs found by me)

### ISSUE THREAD

**Issue by MarcusElg** [MCrafterzz/roadcreator#1]
**Features:**

**Bugs:**

**Comment by anpd03** [comment]
Any plans to add runtime support?

**Comment by MarcusElg** [comment]
For creating roads inside a game? That's would be very different for each game so I probably won't include a finished "package" if some one doesn't send a pr. I think it's a good idea tho to add methouds such as CreateNextPoint() which a system you have created can call. I'm currently working on mesh bending for prefab curves. After that I will focus on fixing bugs as there are so many so it will probably be in the next "feature cycle". Except from that what do you think? It very fun to see that someone accualy came here!

**Comment by MarcusElg** [comment]
Also any bug fixing pull requests are very welcome as I'm developing this by my own at the same time that I have a irl life and games to play.

**Comment by anpd03** [comment]
Yes for creating roads ingame. Mesh bending sounds like a good idea. Will see if I have time to take a closer look and help out :)

**Comment by MCrafterzz** [comment]
@anpd03 After further investigation the problem has to do with rotation some how. The gap filling works when the placed prefabs rotation is 0, 0, 0

**Comment by MarcusElg** [comment]
@anpd03 Everything needed to create roads systems no longer are in the custom editors so if you want you could quite easly add runtime support for creating roads in your game. You just need to call some methouds like  RoadCreator::CreatePoint for example

**Comment by djohns451** [comment]
@MCrafterzz [Unity](https://unity3d.com/learn/tutorials/topics/best-practices/resources-folder) themselves note that we should not be using the Resources feature the way we are right now. At some point, when we include substantial meshes, it will bulk up our memory usage.

> 2.1. Best Practices for the Resources System
> 
> Don't use it.
> 
> This strong recommendation is made for several reasons:
> 
> Use of the Resources folder makes fine-grained memory management more difficult
> 
> Improper use of Resources folders will increase application startup time and the length of builds
> As the number of Resources folders increases, management of the Assets within those folders becomes very difficult
> The Resources system degrades a project's ability to deliver custom content to specific platforms and eliminates the possibility of incremental content upgrades
> AssetBundle Variants are Unity's primary tool for adjusting content on a per-device basis

**Comment by MarcusElg** [comment]
@djohns451 How should I do it then? Also do you have discord?

**Comment by djohns451** [comment]
Well, it doesn't make a lot of sense to have two versions of everything, and AssetDatabase is a very helpful Editor-only class, so I think we should look at abstracting away the Asset-loading portions of the code.

**Comment by djohns451** [comment]
Something like the [GiveMaterial](https://github.com/MicroGSD/RoadArchitect/blob/master/GSDRoadUtilityEditor.cs) method would allow us to use Editor-only methods and runtime methods, depending on environment.
